service: api

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-west-2'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /book/{bookId}
          method: GET

      - http:
          path: /book/list
          method: GET
          
      - http:
        path: /book
        method: POST 
        
      - http:
          path: /{proxy+}
          method: ANY

custom:
  serverless-offline:
    httpPort: 4000
    stageVariables:
      foo: "bar"