version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pukkas-dregistry:testgreen .
      - docker tag pukkas-dregistry:testgreen REGISTRY_URI/pukkas-dregistry:testgreen
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push REGISTRY_URI/pukkas-dregistry:testgreen
